services:
  influxdb:
    image: influxdb:2.7
    volumes:
      - influxdb-data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUX_USERNAME}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUX_PASSWORD}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUX_ORG}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUX_BUCKET}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUX_API_KEY}
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
    depends_on:
      - influxdb
    restart: unless-stopped

  sampler:
    build: .
    devices:
      - /dev/i2c-1:/dev/i2c-1
    environment:
      - INFLUX_BUCKET=${INFLUX_BUCKET}
      - INFLUX_API_KEY=${INFLUX_API_KEY}
      - INFLUX_PORT=8086
      - INFLUX_HOST=influxdb
      - INFLUX_ORG=${INFLUX_ORG}
      - INFLUX_DEVICE_NAME=${INFLUX_DEVICE_NAME}
      - INFLUX_LOCATION=${INFLUX_LOCATION}
      - I2C_PORT=1
      - SAMPLE_PERIOD_MS=2000
      - DB_TYPE=influxdb
      - SENSOR_TYPE=aht20
    depends_on:
      - influxdb
    restart: unless-stopped

volumes:
  influxdb-data:
  grafana-data: