apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    uid: rpi-temp-influxdb      # pin to the same UID as your dashboard expects
    jsonData:
      version: Flux
      organization: $INFLUX_ORG
      defaultBucket: $LOCATION
    secureJsonData:
      token: $INFLUX_API_KEY