{
 "title": "${LOCATION}",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  { "title": "${LOCATION}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Temperature",
   "type": "gauge",
   "description": "Measured using AHT20",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Feel",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Current Humidity",
   "type": "gauge",
   "description": "Measured using AHT20",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Temperature + Humidity",
   "type": "timeseries",
   "description": "Change the time setting above to see more",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"humidity\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Long term highs + lows",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\n  |> set(key: \"_field\", value: \"min\")\n  |> yield(name: \"min\")\n"
    },
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: -1y)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> set(key: \"_field\", value: \"max\")\n  |> yield(name: \"max\")\n"
    }
   ]
  },
  {
   "title": "Daily Highs and Lows",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "fahrenheit" } },
   "targets": [
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: 1d, fn: min, createEmpty: false)\n  |> yield(name: \"mean\")"
    },
    {
     "query": "from(bucket: \"${LOCATION}\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"RPiSensor\")\n  |> filter(fn: (r) => r[\"_field\"] == \"temperature\")\n  |> filter(fn: (r) => r[\"device\"] == \"RPi_aht20\")\n  |> filter(fn: (r) => r[\"location\"] == \"${LOCATION}\")\n  |> aggregateWindow(every: 1d, fn: max, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  }
 ]
}